force-app/main/default/objects/Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>OpportunityAmount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_End__c.field-meta.xml
<CustomField>
    <fullName>Project_End__c</fullName>
    <label>Project End</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Start__c</fullName>
    <label>Project Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/TotalAmountArquitec__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountArquitec__c</fullName>
    <label>TotalAmountArchitech</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TotalAmountConsult__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountConsult__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TotalAmountConsult</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/TotalAmountDeveloper__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountDeveloper__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TotalAmountDeveloper</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Win_or_Lose__c.field-meta.xml
<CustomField>
    <fullName>Win_or_Lose__c</fullName>
    <formula>( Amount__c -  AmountProject__c ) /  Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Win or Lose</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ProfitReportTest.cls
@isTest
public class ProfitReportTest {
    
    @isTest
    static void testGetProject() {
        
        Project__c projectTest= new Project__c(
            Name = 'ProjectX',
            Project_Start__c = Date.today(),
            Project_End__c = Date.today() + 30,
            Amount__c = 200000,
            TotalAmountArquitec__c =30000,
            TotalAmountConsult__c = 4000,
            TotalAmountDeveloper__c = 20000,
            State__c = 'Pre-kickoff'            
        );
        
        insert projectTest;
        
        Decimal AmountProject =  projectTest.TotalAmountArquitec__c + projectTest.TotalAmountConsult__c + projectTest.TotalAmountDeveloper__c;        
        Decimal WinOrLose= ((projectTest.Amount__c - AmountProject ) / projectTest.Amount__c) * 100;        
        Project__c expectedProject = ProfitReport.getProject(projectTest.Id);
        
        System.assertEquals(expectedProject.Win_or_Lose__c, winOrLose );             
    }   
    
}