force-app/main/default/objects/Project__c/fields/Assigned_Hours__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Hours__c</fullName>
    <label>Assigned Hours</label>
    <summarizedField>ResourceProject__c.Assigned_Hours__c</summarizedField>
    <summaryForeignKey>ResourceProject__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_End__c.field-meta.xml
<CustomField>
    <fullName>Project_End__c</fullName>
    <label>Project End</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Start__c</fullName>
    <label>Project Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHourArchitect__c.field-meta.xml
<CustomField>
    <fullName>QuantityHourArchitect__c</fullName>
    <defaultValue>0</defaultValue>
    <label>QuantityHourArchitect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHourConsult__c.field-meta.xml
<CustomField>
    <fullName>QuantityHourConsult__c</fullName>
    <defaultValue>0</defaultValue>
    <label>QuantityHourConsult</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHourDeveloper__c.field-meta.xml
<CustomField>
    <fullName>QuantityHourDeveloper__c</fullName>
    <defaultValue>0</defaultValue>
    <label>QuantityHourDeveloper</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/ResourceProject__c.object-meta.xml
<CustomObject>
    <label>ResourceProject</label>
    <nameField>
        <label>ResourceProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ResourceProjects</relationshipLabel>
    <relationshipName>ResourceProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourceProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResourceProjectTriggerTest.cls
@IsTest
public class ResourceProjectTriggerTest {
	
    @isTest
    public static void testMissingFields() {
        Database.SaveResult saveResult = Database.insert(new ResourceProject__c(), false);
        Assert.isTrue(!saveResult.isSuccess(), 'error must be missing field');
    }
    
    @isTest
    public static void testEndDateGreaterThanStartDate() {
        Project__c project = new Project__c();
        
        project.Name = 'IBM';
        project.Project_Start__c = Date.today() + 30;
        project.Project_End__c = Date.today() + 60;
        project.QuantityHourArchitect__c = 50;
        project.QuantityHourDeveloper__c = 30;
        project.QuantityHourConsult__c = 35;
        project.State__c = 'Pre-kickoff';
        
        insert project;
        
        ResourceProject__c resourceProject = new ResourceProject__c(
            Rol__c='Developer', 
            Project__c = project.Id,
            User__c = UserInfo.getUserId(),
            Assigned_Hours__c = 30,
            Name ='Developer',
            Start_Date__c = Date.today(),
            End_Date__c =  Date.today() - 30);
        
        Database.SaveResult saveResult = Database.insert(resourceProject, false);
        Assert.isTrue(!saveResult.isSuccess(), 'error validation rule end date must be greater than start date');
    }
    
    @isTest
    public static void testAvailabiltyResource() {
        
        List<Project__c> projects = new List<Project__c>();
        List<ResourceProject__c> resourceProjects = new List<ResourceProject__c>();
        
        Project__c project = new Project__c();
        
        project.Name = 'IBM';
        project.Project_Start__c = Date.today() + 30;
        project.Project_End__c = Date.today() + 60;
        project.QuantityHourArchitect__c = 50;
        project.QuantityHourDeveloper__c = 30;
        project.QuantityHourConsult__c = 35;
        project.State__c = 'Pre-kickoff';
        
        Project__c otherProject = new Project__c();
        
        otherProject.Name = 'Amazon';
        otherProject.Project_Start__c = Date.today() + 20;
        otherProject.Project_End__c = Date.today() + 50;
        otherProject.QuantityHourArchitect__c = 50;
        otherProject.QuantityHourDeveloper__c = 30;
        otherProject.QuantityHourConsult__c = 35;
        otherProject.State__c = 'Pre-kickoff';
        
        projects.add(project);
        projects.add(otherProject);
         
        insert projects;
        
        ResourceProject__c resourceProject = new ResourceProject__c(
            Rol__c='Developer', 
            Project__c = project.Id,
            User__c = UserInfo.getUserId(),
            Assigned_Hours__c = 30,
            Name ='Developer',
            Start_Date__c = Date.today() + 30,
            End_Date__c =  Date.today() + 60);
        
       
        
        ResourceProject__c otherResourceProject = new ResourceProject__c(
            Rol__c='Developer', 
            Project__c = otherProject.Id,
            User__c = UserInfo.getUserId(),
            Assigned_Hours__c = 30,
            Name ='Developer',
            Start_Date__c = Date.today() + 20,
            End_Date__c =  Date.today() + 50);
        
        
        resourceProjects.add(resourceProject);
        resourceProjects.add(otherResourceProject); 
        
        Database.SaveResult[] saveResults = Database.insert(resourceProjects, false);
        
        for(Database.SaveResult saveResult: saveResults) {
            Assert.isTrue(saveResult.isSuccess());        
        }
    }
}