force-app/main/default/objects/Project__c/fields/Project_End__c.field-meta.xml
<CustomField>
    <fullName>Project_End__c</fullName>
    <label>Project End</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Start__c</fullName>
    <label>Project Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHourArchitect__c.field-meta.xml
<CustomField>
    <fullName>QuantityHourArchitect__c</fullName>
    <defaultValue>0</defaultValue>
    <label>QuantityHourArchitect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHourConsult__c.field-meta.xml
<CustomField>
    <fullName>QuantityHourConsult__c</fullName>
    <defaultValue>0</defaultValue>
    <label>QuantityHourConsult</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/QuantityHourDeveloper__c.field-meta.xml
<CustomField>
    <fullName>QuantityHourDeveloper__c</fullName>
    <defaultValue>0</defaultValue>
    <label>QuantityHourDeveloper</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectItem__c/ProjectItem__c.object-meta.xml
<CustomObject>
    <label>Project Item</label>
    <nameField>
        <label>ProjectItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Items</relationshipLabel>
    <relationshipName>Project_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectItem__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResourceProject__c/ResourceProject__c.object-meta.xml
<CustomObject>
    <label>ResourceProject</label>
    <nameField>
        <label>ResourceProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ResourceProjects</relationshipLabel>
    <relationshipName>ResourceProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourceProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Rate_p_hour__c.field-meta.xml
<CustomField>
    <fullName>Rate_p_hour__c</fullName>
    <label>Rate p/hour</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResourceAllocation.cls
public with sharing class ResourceAllocation {

    @AuraEnabled(Cacheable=true)
    public static List<User> getResources(Id projectId) {

        Project__c project = [
                SELECT Id, Project_Start__c, Project_End__c
                FROM Project__c
                WHERE Id =: projectId
        ];

        Map<Id, User> userMap = new Map<Id, User>([
                SELECT Id, Name, Profile.Name, UserRole.Name, Rate_p_hour__c
                FROM User
                WHERE Profile.Name IN ('Developer', 'Architect', 'Consultant')
        ]);

        List<User> complementUsers = [
                SELECT Id, Name, Profile.Name, UserRole.Name, Rate_p_hour__c
                FROM User
                WHERE Profile.Name IN ('Developer', 'Architect', 'Consultant')
                AND Id IN (
                        SELECT User__c FROM ResourceProject__c
                        WHERE Start_Date__c != NULL AND End_Date__c != NULL
                        AND (( Start_Date__c >=: project.Project_Start__c AND End_Date__c >=: project.Project_Start__c)
                        AND ( Start_Date__c <=: project.Project_End__c AND End_Date__c <=: project.Project_End__c))
                        AND Project__c =: projectId
                )
        ];

        for (User user: complementUsers) {
            if (userMap.containsKey(user.Id)) {
                userMap.remove(user.Id);
            }
        }

        return userMap.values();
    }

    @AuraEnabled(Cacheable=true)
    public static List<ProjectItem__c> getProjectItems(Id projectId) {
        return [
            SELECT Id, rol__c, Quantity__c, Project__c,
                    Project__r.Project_Start__c, Project__r.Project_End__c,
                    Project__r.QuantityHourDeveloper__c, Project__r.QuantityHourArchitect__c, Project__r.QuantityHourConsult__c
            FROM ProjectItem__c
            WHERE project__c =: projectId
        ];
    }

    @AuraEnabled
    public static void createResourceProject(String jsonResourceProjects) {
        List<ResourceProject__c> resourceprojects = (List<ResourceProject__c>) JSON.deserializeStrict(jsonResourceProjects, List<ResourceProject__c>.class);
        Database.insert(resourceprojects);
    }

}