force-app/main/default/objects/Assigment_Task__c/Assigment_Task__c.object-meta.xml
<CustomObject>
    <label>Assigment Task</label>
    <nameField>
        <label>Assigment Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigment_Task__c/fields/ResourceProject__c.field-meta.xml
<CustomField>
    <fullName>ResourceProject__c</fullName>
    <label>ResourceProject</label>
    <referenceTo>ResourceProject__c</referenceTo>
    <relationshipLabel>Assigment Tasks</relationshipLabel>
    <relationshipName>Assigment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Init</fullName>
                <default>true</default>
                <label>Not Init</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/ResourceProject__c.object-meta.xml
<CustomObject>
    <label>ResourceProject</label>
    <nameField>
        <label>ResourceProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ResourceProjects</relationshipLabel>
    <relationshipName>ResourceProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectTaskVerificator.cls
public with sharing class ProjectTaskVerificator {

    public void onBeforeUpdate(List<Project__c> newProjects, Map<Id, Project__c> oldProjectMap) {

        Set<Id> projectIds = new Set<Id>();

        for (Project__c newProject: newProjects) {
            Boolean isNewCompleted = newProject.State__c == 'Completed';
            Boolean isNotOldCompleted = oldProjectMap.get(newProject.Id).State__c != 'Completed';
            if (isNotOldCompleted && isNewCompleted) {
                projectIds.add(newProject.Id);
            }
        }

        List<Assigment_Task__c> assigmentTasks = [
          SELECT Id, ResourceProject__r.Project__c
          FROM Assigment_Task__c
          WHERE ResourceProject__r.Project__c IN: projectIds
                AND Status__c != 'Completed'
        ];

        System.debug(assigmentTasks);

        Map<Id, Integer> projectMapIntegersByIds = new Map<Id, Integer>();

        for (Assigment_Task__c assigmentTask: assigmentTasks) {
            Id projectId = assigmentTask.ResourceProject__r.Project__c;
            if (!projectMapIntegersByIds.containsKey(projectId)) {
                projectMapIntegersByIds.put(projectId, 1);
            } else {
                Integer quantityOfNotCompleted = projectMapIntegersByIds.get(projectId);
                projectMapIntegersByIds.put(projectId, quantityOfNotCompleted + 1);
            }
        }

        for (Project__c newProject: newProjects) {
            if (projectMapIntegersByIds.containsKey(newProject.Id)) {
                newProject.addError('The proyect can\'t be updated to Completed because it has open Tasks');
            }
        }

    }

}