force-app/main/default/objects/Assigment_Task__c/Assigment_Task__c.object-meta.xml
<CustomObject>
    <label>Assigment Task</label>
    <nameField>
        <label>Assigment Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigment_Task__c/fields/ReportedHours__c.field-meta.xml
<CustomField>
    <fullName>ReportedHours__c</fullName>
    <label>ReportedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/ResourceProject__c.field-meta.xml
<CustomField>
    <fullName>ResourceProject__c</fullName>
    <label>ResourceProject</label>
    <referenceTo>ResourceProject__c</referenceTo>
    <relationshipLabel>Assigment Tasks</relationshipLabel>
    <relationshipName>Assigment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Init</fullName>
                <default>true</default>
                <label>Not Init</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/ResourceProject__c.object-meta.xml
<CustomObject>
    <label>ResourceProject</label>
    <nameField>
        <label>ResourceProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ResourceProjects</relationshipLabel>
    <relationshipName>ResourceProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssignedTaskTest.cls
@IsTest
public class AssignedTaskTest {
    
    @IsTest
    public static void testGetResourceProjects() {
		
		new AssignedTaskBuilderTest().build();
       
        List<ResourceProject__c> ExpectedresourceProjects = AsignedTaskController.getResourceProjects();

        for (ResourceProject__c ExpectedresourceProject: ExpectedresourceProjects){
                Assert.areEqual(ExpectedresourceProject.Project__r.Name, 'Project');
            for(Assigment_Task__c expectedAssigmentTask:  ExpectedresourceProject.Assigment_Tasks__r) {
                Assert.areEqual(expectedAssigmentTask.Status__c, 'In Progress');
                Assert.areEqual(expectedAssigmentTask.EstimatedHours__c, 100);
                Assert.areEqual(expectedAssigmentTask.ReportedHours__c, 20);
            }
        }
    }

    @IsTest
    public static void testUpdateReportedHours() {

		AssignedTaskBuilderTest assignedTaskBuilderTest = new AssignedTaskBuilderTest();
        assignedTaskBuilderTest.build();
        Assigment_Task__c assigmentTask = assignedTaskBuilderTest.obtainAssigmentTask();

        assigmentTask.ReportedHours__c = 40;
        String jsonAssigmentTask = JSON.serialize(assigmentTask);
        
        AsignedTaskController.updateReportedHours(jsonAssigmentTask);

        Assigment_Task__c assigmentTaskExpected = [
                SELECT Name, Description__c, EstimatedHours__c, ReportedHours__c
                FROM Assigment_Task__c
                WHERE Id =: assigmentTask.Id
        ];

        Assert.areEqual(assigmentTaskExpected.Name, 'Task0');
        Assert.areEqual(assigmentTaskExpected.Description__c, 'Description');
        Assert.areEqual(assigmentTaskExpected.EstimatedHours__c, 100);
        Assert.areEqual(assigmentTaskExpected.ReportedHours__c, 40);
    }
}