force-app/main/default/objects/Assigment_Task__c/Assigment_Task__c.object-meta.xml
<CustomObject>
    <label>Assigment Task</label>
    <nameField>
        <label>Assigment Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigment_Task__c/fields/ReportedHours__c.field-meta.xml
<CustomField>
    <fullName>ReportedHours__c</fullName>
    <label>ReportedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/ResourceProject__c.field-meta.xml
<CustomField>
    <fullName>ResourceProject__c</fullName>
    <label>ResourceProject</label>
    <referenceTo>ResourceProject__c</referenceTo>
    <relationshipLabel>Assigment Tasks</relationshipLabel>
    <relationshipName>Assigment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Init</fullName>
                <default>true</default>
                <label>Not Init</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Assigned_Hours__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Hours__c</fullName>
    <label>Assigned Hours</label>
    <summarizedField>ResourceProject__c.Assigned_Hours__c</summarizedField>
    <summaryForeignKey>ResourceProject__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_End__c.field-meta.xml
<CustomField>
    <fullName>Project_End__c</fullName>
    <label>Project End</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Start__c.field-meta.xml
<CustomField>
    <fullName>Project_Start__c</fullName>
    <label>Project Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/ResourceProject__c.object-meta.xml
<CustomObject>
    <label>ResourceProject</label>
    <nameField>
        <label>ResourceProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ResourceProjects</relationshipLabel>
    <relationshipName>ResourceProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourceProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectTaskVerificatorBuilderTest.cls
@IsTest
public class ProjectTaskVerificatorBuilderTest {
	
    public static final Integer LOOPS = 3;
    
    private Project__c project;
    private ResourceProject__c resourceProject;
    private List<Assigment_Task__c> assigmentTasks;
    
    public ProjectTaskVerificatorBuilderTest() {
        assigmentTasks = new List<Assigment_Task__c>();
    }
    
    public void buildStatus(String status) {
        buildProject();
        buildResourceProject();
        updateResourceProject();
        buildAssigmentTask(status);
    }
    
    public Project__c obtainProject() {
        return project;
    }
    
    public Assigment_Task__c obtainAssigmentTask() {
        return assigmentTasks[0];
    }
    
    private void buildProject() {
        project = new Project__c(
                Name = 'Project',
                Project_Start__c = Date.today(),
                Project_End__c = Date.today(),
                State__c = 'Pre-kickoff'
        );

        insert project;
    }
    
    private void buildResourceProject() {
        resourceProject = new ResourceProject__c(
                Name = 'ResourceProject',
                Project__c = project.Id,
                Start_Date__c = Date.today(),
                End_Date__c = Date.today(),
                User__c = UserInfo.getUserId(),
                Rol__c = 'Developer',
                Assigned_Hours__c = 12
        );
        insert resourceProject;
    }
    
    private void updateResourceProject() {
        project.State__c = 'In Progress';
        update project;
    }
    
    private void buildAssigmentTask(String status) {
        for (Integer index = 0; index <= LOOPS; index++) {
            Assigment_Task__c assigmentTask = new Assigment_Task__c(
                    Name = 'Task' + index,
                    Description__c = 'Description',
                    EstimatedHours__c = 100,
                    ReportedHours__c = 20,
                    ResourceProject__c = resourceProject.Id,
                    Status__c = status
            );
            assigmentTasks.add(assigmentTask);
        }
        insert assigmentTasks;
    }
    
}