force-app/main/default/objects/Assigment_Task__c/Assigment_Task__c.object-meta.xml
<CustomObject>
    <label>Assigment Task</label>
    <nameField>
        <label>Assigment Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigment Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigment_Task__c/fields/Init__c.field-meta.xml
<CustomField>
    <fullName>Init__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &quot;Not Init&quot;) &amp;&amp; ReportedHours__c = 0, false, true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Init</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/ReportedHours__c.field-meta.xml
<CustomField>
    <fullName>ReportedHours__c</fullName>
    <label>ReportedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/ResourceProject__c.field-meta.xml
<CustomField>
    <fullName>ResourceProject__c</fullName>
    <label>ResourceProject</label>
    <referenceTo>ResourceProject__c</referenceTo>
    <relationshipLabel>Assigment Tasks</relationshipLabel>
    <relationshipName>Assigment_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assigment_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Init</fullName>
                <default>true</default>
                <label>Not Init</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceProject__c/ResourceProject__c.object-meta.xml
<CustomObject>
    <label>ResourceProject</label>
    <nameField>
        <label>ResourceProject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ResourceProjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>ResourceProjects</relationshipLabel>
    <relationshipName>ResourceProjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ResourceProject__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResourceProjects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignedTask.cls
public with sharing class AssignedTask {

    public List<ResourceProject__c> getResourceProjects() {
        return [
                SELECT Id, Project__r.Name, (
                        SELECT Id, Name, Status__c, EstimatedHours__c, ReportedHours__c, Init__c
                        FROM Assigment_Tasks__r
                        WHERE Status__c != 'Completed'
                )
                FROM ResourceProject__c
                WHERE User__c =: UserInfo.getUserId()
                    AND Id IN ( SELECT ResourceProject__c FROM Assigment_Task__c )
        ];      
    }

    public void updateReportedHours(String jsonAssigmentTask) {
        Assigment_Task__c assigmentTask = (Assigment_Task__c) JSON.deserializeStrict(jsonAssigmentTask, Assigment_Task__c.class);
        Database.update(assigmentTask);
    }
    
}